CREATE TABLE PERSON (
    id INTEGER generated by default as identity (start with 1),
    name VARCHAR(30),
    country  VARCHAR(100),
    primary key (id)
);

CREATE TABLE MESSAGES (
    id varchar(50) NOT NULL,
    type varchar(20) NOT NULL,
    payload varchar(160) NOT NULL,
    created_at timestamp,
    PRIMARY KEY (id)
);
